name: Publish RELEASE version

on: 
  push:
    branches:
    - release
    paths-ignore:
      - '.github/**'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build

  version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: beta
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: git config --global user.name '[Workflow]'
      - run: git config --global user.email '<>'
      - run: npm version minor -m "[RELEASE] %s"
      - run: npm update homebridge-elero-stick
      - run: git push --follow-tags

  publish:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v2
        with:
          ref: beta
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
